//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChitTietDonHang = new HashSet<ChitTietDonHang>();
        }
    
        public int IDDonHang { get; set; }
        public string ShipTenNguoiDat { get; set; }
        public string ShipSoDienThoai { get; set; }
        public string ShipDiaChi { get; set; }
        public string ShipEmail { get; set; }
        public string ShipGhiChu { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string TrangThaiDonHang { get; set; }
        public string UserName { get; set; }
        public decimal TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitTietDonHang> ChitTietDonHang { get; set; }
    }
}
