//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChitTietDonHang = new HashSet<ChitTietDonHang>();
        }
    
        public int IDSanPham { get; set; }
        public int IDDanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public string Hinh { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string GioiThieu { get; set; }
        public int DonGia { get; set; }
        public int GiaKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public int SoLuongTon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitTietDonHang> ChitTietDonHang { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
    }
}
